#!/usr/bin/env php
<?php declare(strict_types=1);

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}

if ((!$loader = includeIfExists(__DIR__.'/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../autoload.php'))) {
    die('You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL);
}

use SupportPal\LanguageTools\Command\CompareCommand;
use SupportPal\LanguageTools\Command\SyncCommand;
use Symfony\Component\Console\Application;

$console = new Application('SupportPal Language Tools');
$console->add(new CompareCommand);
$console->add(new SyncCommand);
$console->run();
